language: go

go: 
  - tip

install:
  - go get github.com/BurntSushi/toml
  - go get github.com/gin-gonic/gin
  - go get github.com/shirou/gopsutil/cpu
  - go get github.com/shirou/gopsutil/mem
  - go get github.com/shirou/gopsutil/disk
  - go get github.com/stretchr/testify/assert
  - go get github.com/julianespinel/mbu/stats
  - go get github.com/julianespinel/mbu/config

script: 
  - go test -v ./...
